version: 1.2
workflows:
   - subclass: WDL
     primaryDescriptorPath: /wdl/HelloWorld.wdl
     testParameterFiles:
         - /wdl/hello.json
     name: HelloWorld
   - subclass: CWL
      primaryDescriptorPath: /cwl/hello.cwl
      testParameterFiles:
         - /cwl/hello.json
       name: hello
